# Generated by Django 3.1.7 on 2022-03-01 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_auto_20220301_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(choices=[('NA', 'None Selected'), ('NSW', 'New South Wales'), ('VIC', 'Victoria'), ('ACT', 'Australian Captial Territory'), ('QLD', 'Queensland'), ('SA', 'South Australia'), ('NT', 'Northern Territory'), ('WA', 'Western Australia'), ('TAS', 'Tasmania')], default='NA', max_length=3),
        ),
    ]
