# Generated by Django 3.1.7 on 2022-03-01 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0003_auto_20220301_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(choices=[('None Selected', 'None Selected'), ('New South Wales', 'New South Wales'), ('Victoria', 'Victoria'), ('Australian Capital Territory', 'Australian Captial Territory'), ('Queensland', 'Queensland'), ('South Australia', 'South Australia'), ('Northern Territory', 'Northern Territory'), ('Western Australia', 'Western Australia'), ('Tasmania', 'Tasmania')], default='None Selected', max_length=55),
        ),
    ]
