# Generated by Django 3.1.7 on 2022-02-25 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graph_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('street', models.CharField(max_length=55)),
                ('city', models.CharField(max_length=55)),
                ('state', models.CharField(choices=[('NA', 'None Selected'), ('NSW', 'New South Wales'), ('VIC', 'Victoria'), ('ACT', 'Australian Captial Territory'), ('QLD', 'Queensland'), ('SA', 'South Australia'), ('NT', 'Northern Territory'), ('WA', 'Western Australia'), ('TAS', 'Tasmania')], default='NA', max_length=3)),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address', to='graph_api.person')),
            ],
        ),
    ]
